### ISSUE TITLE
Add undo functionality to checking items off on a list in a future issue - Aubrey

### ISSUE THREAD

**Issue by luisaugusto** [the-collab-lab/tcl-51-smart-shopping-list#25]

**Comment by a-fink** [comment]
- Need to add some way to store the most recent dateLastPurchased (2nd property, or make dateLastPurchased an array etc) so we can restore it if the user unchecks the checkbox. 
- When a purchase is undone, we we will need to update the dateNextPurchased using the old data too. We could store the most recent calculation of dateNextPurchased in addition to the current one, or look at using the older dateLastPurchased to recalculate.
- Need to alter our change handler for the ListItem checkboxes and the updateItem function to handle this behavior and the new shape of our data we decide on
- Also need to account for how to update the shape of the data on older items made before this change, and/or manually change/delete old lists.

**Comment by a-fink** [comment]
Will unfortunately not fit into the main project timeline. Stretch goal for our own versions after completion.
